### ISSUE TITLE
Use die instead of exit(1) - RPC error response

### ISSUE THREAD

**Issue by regcostajr** [whindsx/Bitcoin-RPC-Client#1]
Perl version: v5.26.2 x86_64-linux

If the RPC call returns an error for sample: 
`error code: -5, error message: Invalid address (getaddressinfo)`

The message will be printed but we can't catch the exception in the tests because of the use of `exit(1)` and the bellow message will be triggered:

```
A context appears to have been destroyed without first calling release().
Based on $@ it does not look like an exception was thrown (this is not always
a reliable test)

This is a problem because the global error variables ($!, $@, and $?) will
not be restored. In addition, some release callbacks will not work properly from
inside a DESTROY method.
```
Following the exit docs https://perldoc.perl.org/functions/exit.html:

```
Don't use exit to abort a subroutine if there's any chance that someone might want to trap whatever error happened. Use die instead, which can be trapped by an eval.
```
https://github.com/whindsx/Bitcoin-RPC-Client/blob/365c1ad96a4b3e1f2fdfa6ed7ca8fc952bc9b342/lib/Bitcoin/RPC/Client.pm#L90

**Comment by whindsx** [comment]
Thanks!


As a side note:

By removing the handler there is a loss/change in functionality during "debug" mode. Now execution will end and the error message will be printed. Previously the job would continue execution even if an error was encountered and print only the data from the HTTP Request/Response.

But honestly I don't see an issue with this as to my knowledge nobody uses the debug feature, plus ending execution if something goes wrong is probably safer in general.
